import { NextRequest, NextResponse } from "next/server";
import { isProUser } from "@/lib/stripe";

type GenerateBody = {
  template?: string;
  tone?: string;
  length?: string;
  company?: string;
  client?: string;
  topic?: string;
  details?: string;
};

const TEMPLATE_LABELS: Record<string, string> = {
  business: "Business Proposal",
  project: "Project Proposal",
  sales: "Sales Proposal",
  report: "Executive Report",
  rfp: "RFP Response",
};

function buildMockDocument(body: Required<GenerateBody>): string {
  const templateLabel = TEMPLATE_LABELS[body.template] ?? "Business Proposal";
  const date = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  return `${templateLabel.toUpperCase()}

Prepared by: ${body.company}
Prepared for: ${body.client}
Date: ${date}
Subject: ${body.topic}

────────────────────────────────────────

1. EXECUTIVE SUMMARY

${body.company} is pleased to present this ${templateLabel.toLowerCase()} to ${body.client} regarding ${body.topic}.

This document outlines our recommended approach, expected outcomes, and the value we bring to the engagement. Our goal is to deliver a clear, actionable plan tailored to your priorities.

Key points from your brief:
${body.details}

────────────────────────────────────────

2. UNDERSTANDING YOUR NEEDS

Based on the information provided, ${body.client} is seeking a partner who can deliver results on ${body.topic} with a ${body.tone} approach and ${body.length} level of detail.

We have structured this proposal to address your goals, constraints, and success criteria while remaining practical and easy to act on.

────────────────────────────────────────

3. PROPOSED APPROACH

Phase 1 — Discovery & Alignment
• Stakeholder interviews and requirements gathering
• Current-state assessment
• Success metrics definition

Phase 2 — Solution Design
• Solution architecture and deliverables
• Timeline and milestone plan
• Risk assessment and mitigation

Phase 3 — Delivery & Enablement
• Implementation and iterative reviews
• Training and knowledge transfer
• Handover and support plan

────────────────────────────────────────

4. SCOPE & DELIVERABLES

• Detailed project plan and roadmap
• Core deliverables aligned to ${body.topic}
• Progress reports and milestone reviews
• Final documentation and recommendations

────────────────────────────────────────

5. TIMELINE (ILLUSTRATIVE)

Week 1–2: Discovery & planning
Week 3–6: Core delivery
Week 7–8: Review, refinement, and handover

Exact dates will be confirmed jointly with ${body.client}.

────────────────────────────────────────

6. INVESTMENT

Pricing is available upon request and can be structured as fixed-fee, milestone-based, or retainer — depending on scope. We recommend a discovery workshop to finalize estimates.

────────────────────────────────────────

7. WHY ${body.company.toUpperCase()}

• Domain expertise relevant to ${body.topic}
• Clear communication and ${body.tone} collaboration style
• Focus on measurable outcomes for ${body.client}
• Transparent process from kickoff to delivery

────────────────────────────────────────

8. NEXT STEPS

1. Review this draft with your team
2. Schedule a short alignment call
3. Confirm scope, timeline, and commercial terms
4. Kick off Phase 1

We look forward to partnering with ${body.client}.

Sincerely,
${body.company}

— Generated by Propogen AI (demo template)
`;
}

async function generateWithXai(body: Required<GenerateBody>): Promise<string | null> {
  const apiKey = process.env.XAI_API_KEY;
  if (!apiKey) return null;

  const templateLabel = TEMPLATE_LABELS[body.template] ?? "Business Proposal";
  const lengthHint =
    body.length === "short"
      ? "Keep it concise (about 400–600 words)."
      : body.length === "long"
        ? "Make it detailed (about 1200–1800 words)."
        : "Aim for a medium length (about 700–1000 words).";

  const prompt = `You are Propogen AI, an expert business writer. Write a polished ${templateLabel} with a ${body.tone} tone.

Company (author): ${body.company}
Client / audience: ${body.client}
Topic / title: ${body.topic}
Key details: ${body.details}

${lengthHint}

Use clear section headings, professional language, and actionable next steps. Output plain text only (no markdown code fences).`;

  try {
    const res = await fetch("https://api.x.ai/v1/chat/completions", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${apiKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: "grok-4.5",
        messages: [
          {
            role: "system",
            content:
              "You write professional business proposals and documents. Be clear, credible, and well-structured.",
          },
          { role: "user", content: prompt },
        ],
        temperature: 0.7,
      }),
    });

    if (!res.ok) {
      console.error("xAI error:", await res.text());
      return null;
    }

    const data = (await res.json()) as {
      choices?: { message?: { content?: string } }[];
    };
    const text = data.choices?.[0]?.message?.content?.trim();
    return text || null;
  } catch (err) {
    console.error("xAI request failed:", err);
    return null;
  }
}

export async function POST(req: NextRequest) {
  let body: GenerateBody;
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON body" }, { status: 400 });
  }

  const company = body.company?.trim() ?? "";
  const client = body.client?.trim() ?? "";
  const topic = body.topic?.trim() ?? "";
  const details = body.details?.trim() ?? "";

  if (!company || !client || !topic || !details) {
    return NextResponse.json(
      { error: "Please fill in company, client, topic, and details." },
      { status: 400 },
    );
  }

  const payload: Required<GenerateBody> = {
    template: body.template || "business",
    tone: body.tone || "professional",
    length: body.length || "medium",
    company,
    client,
    topic,
    details,
  };

  const pro = await isProUser();

  // Live AI is a Pro feature (requires successful Stripe checkout cookie + XAI key)
  if (pro) {
    const aiDoc = await generateWithXai(payload);
    if (aiDoc) {
      return NextResponse.json({
        document: aiDoc,
        source: "Grok · Pro",
        isPro: true,
      });
    }
    return NextResponse.json({
      document: buildMockDocument(payload),
      source:
        "Pro unlocked, but AI unavailable (check XAI_API_KEY) — demo template used",
      isPro: true,
    });
  }

  return NextResponse.json({
    document: buildMockDocument(payload),
    source: "Free demo template · Upgrade to Pro for live AI",
    isPro: false,
  });
}
